### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by praeludiumOrbis** [WhosMyName/ProxLoadMe#1]
I gave it the URL in the right format, yet it says that it's invalid.

[Here's the log](https://github.com/WhosMyName/ProxLoadMe/files/4827110/log.txt).

**Comment by WhosMyName** [comment]
Heyyo,
thanks for opening an Issue.

I will have a look at the error and see how i can fix it.
To be honest, I haven't used this script in ages, but based on your Issues this has gotten way more problematic than I expected.

**Comment by WhosMyName** [comment]
Latest Commit (f35af5f ) should fix this Issue.
Reopen if there're some problems <3
